#------------------------------------------------------------------------------
# Makefile
#
# Simple makefile for installing the scripts.
#------------------------------------------------------------------------------

# Target for the executable
all:

install:
	install -d $(PREFIX)/bin
	install -m 755 update_narr_aux_data_from_CISL_RDA.py $(PREFIX)/bin
	install -m 644 lst_auxillary.config.example $(PREFIX)/bin

clean:

