#!/bin/sh
# download NARR data

yymm=yearmo
date=yearmody
hr=rh        	#specify in 3 hour increments

a="http://nomads.ncdc.noaa.gov/data/narr/$yymm/$date/narr-a_221_${date}_${hr}00_000"
echo $a.inv
./get_inv.pl $a.inv | egrep "HGT:.00|HGT:.25|HGT:.50|HGT:.75" | ./get_grib.pl $a.grb HGT.grb
echo "done"
