
# A simple tool to reformat the LUT's generated by the IDL code

import os
import sys
from argparse import ArgumentParser


if __name__ == '__main__':
    """Reformat the file to what is expected"""

    description = 'Reformat LUT files'
    parser = ArgumentParser(description=description)

    parser.add_argument('--input',
                        action='store',
                        dest='input',
                        required=True,
                        help='The filename for the input')

    parser.add_argument('--output',
                        action='store',
                        dest='output',
                        required=True,
                        help='The filename for the output')

    args = parser.parse_args()

    with open(args.input, 'r') as in_fd:
        with open(args.output, 'w') as out_fd:

            for line in in_fd:
                data = line.strip().split()
                out_fd.write('{0:5.2f} {1:+11.9f}\n'
                             .format(float(data[0]), float(data[1])))
