#!/bin/sh
./a.out HGT.grb -d 1 -text -o HGT/100.txt
./a.out HGT.grb -d 2 -text -o HGT/125.txt
./a.out HGT.grb -d 3 -text -o HGT/150.txt
./a.out HGT.grb -d 4 -text -o HGT/175.txt
./a.out HGT.grb -d 5 -text -o HGT/200.txt
./a.out HGT.grb -d 6 -text -o HGT/225.txt
./a.out HGT.grb -d 7 -text -o HGT/250.txt
./a.out HGT.grb -d 8 -text -o HGT/275.txt
./a.out HGT.grb -d 9 -text -o HGT/300.txt
./a.out HGT.grb -d 10 -text -o HGT/350.txt
./a.out HGT.grb -d 11 -text -o HGT/400.txt
./a.out HGT.grb -d 12 -text -o HGT/450.txt
./a.out HGT.grb -d 13 -text -o HGT/500.txt
./a.out HGT.grb -d 14 -text -o HGT/550.txt
./a.out HGT.grb -d 15 -text -o HGT/600.txt
./a.out HGT.grb -d 16 -text -o HGT/650.txt
./a.out HGT.grb -d 17 -text -o HGT/700.txt
./a.out HGT.grb -d 18 -text -o HGT/725.txt
./a.out HGT.grb -d 19 -text -o HGT/750.txt
./a.out HGT.grb -d 20 -text -o HGT/775.txt
./a.out HGT.grb -d 21 -text -o HGT/800.txt
./a.out HGT.grb -d 22 -text -o HGT/825.txt
./a.out HGT.grb -d 23 -text -o HGT/850.txt
./a.out HGT.grb -d 24 -text -o HGT/875.txt
./a.out HGT.grb -d 25 -text -o HGT/900.txt
./a.out HGT.grb -d 26 -text -o HGT/925.txt
./a.out HGT.grb -d 27 -text -o HGT/950.txt
./a.out HGT.grb -d 28 -text -o HGT/975.txt
./a.out HGT.grb -d 29 -text -o HGT/1000.txt
mv HGT.grb  HGT/HGT.grb

