
# A simple tool to reformat the LUT's generated by the IDL code

import os
import sys

with open('L8_B11_LUT.txt', 'r') as in_fd:
    with open('L8_B11_Brightness_Temperature_LUT.txt', 'w') as out_fd:

        for line in in_fd:
            out_fd.write(' '.join(line.strip().split()) + '\n')
