#!/bin/sh
./a.out TMP.grb -d 1 -text -o TMP/100.txt
./a.out TMP.grb -d 2 -text -o TMP/125.txt
./a.out TMP.grb -d 3 -text -o TMP/150.txt
./a.out TMP.grb -d 4 -text -o TMP/175.txt
./a.out TMP.grb -d 5 -text -o TMP/200.txt
./a.out TMP.grb -d 6 -text -o TMP/225.txt
./a.out TMP.grb -d 7 -text -o TMP/250.txt
./a.out TMP.grb -d 8 -text -o TMP/275.txt
./a.out TMP.grb -d 9 -text -o TMP/300.txt
./a.out TMP.grb -d 10 -text -o TMP/350.txt
./a.out TMP.grb -d 11 -text -o TMP/400.txt
./a.out TMP.grb -d 12 -text -o TMP/450.txt
./a.out TMP.grb -d 13 -text -o TMP/500.txt
./a.out TMP.grb -d 14 -text -o TMP/550.txt
./a.out TMP.grb -d 15 -text -o TMP/600.txt
./a.out TMP.grb -d 16 -text -o TMP/650.txt
./a.out TMP.grb -d 17 -text -o TMP/700.txt
./a.out TMP.grb -d 18 -text -o TMP/725.txt
./a.out TMP.grb -d 19 -text -o TMP/750.txt
./a.out TMP.grb -d 20 -text -o TMP/775.txt
./a.out TMP.grb -d 21 -text -o TMP/800.txt
./a.out TMP.grb -d 22 -text -o TMP/825.txt
./a.out TMP.grb -d 23 -text -o TMP/850.txt
./a.out TMP.grb -d 24 -text -o TMP/875.txt
./a.out TMP.grb -d 25 -text -o TMP/900.txt
./a.out TMP.grb -d 26 -text -o TMP/925.txt
./a.out TMP.grb -d 27 -text -o TMP/950.txt
./a.out TMP.grb -d 28 -text -o TMP/975.txt
./a.out TMP.grb -d 29 -text -o TMP/1000.txt
mv TMP.grb  TMP/TMP.grb

