#!/bin/sh
# download NARR data

yymm=yearmo
date=yearmody
hr=rh        	#specify in 3 hour increments

a="https://nomads.ncdc.noaa.gov/data/narr/$yymm/$date/narr-a_221_${date}_${hr}00_000"
echo $a.inv
./get_inv.pl $a.inv | egrep "SPFH:.00|SPFH:.25|SPFH:.50|SPFH:.75" | ./get_grib.pl $a.grb SHUM.grb
echo "done"
